apiVersion: v1
kind: Service
metadata:
  name: {{ include "pihole-jfwenisch.fullname" . }}-dhcp
  labels:
    {{- include "pihole-jfwenisch.labels" . | nindent 4 }}
spec:
  ports:
    - port: 67
      targetPort: 67
      protocol: UDP
      name: dhcp
  externalIPs:
  - {{ .Values.ipaddress }}
  selector:
    {{- include "pihole-jfwenisch.selectorLabels" . | nindent 4 }}
