apiVersion: v1
kind: Service
metadata:
  name: {{ include "pihole-jfwenisch.fullname" . }}
  labels:
    {{- include "pihole-jfwenisch.labels" . | nindent 4 }}
spec:
  type: NodePort
  ports:
    - port: 53
      targetPort: 53
      protocol: TCP
      name: dns-tcp
    - port: 53
      targetPort: 53
      protocol: UDP
      name: dns-udp
    - port: 67
      targetPort: 67
      protocol: UDP
      name: dhcp
    - port: 80
      targetPort: 80
      protocol: TCP
      name: http
    - port: 443
      targetPort: 443
      protocol: TCP
      name: https
  selector:
    {{- include "pihole-jfwenisch.selectorLabels" . | nindent 4 }}
